@echo off
set PGPASSWORD=Ferchitovil1830
echo Adding DeviceId column to LocationHistories...
"C:\Program Files\PostgreSQL\17\bin\psql.exe" -h localhost -p 5432 -U postgres -d CattleTrackingDB -c "ALTER TABLE \"LocationHistories\" ADD COLUMN IF NOT EXISTS \"DeviceId\" VARCHAR(100);"
echo Making AnimalId nullable...
"C:\Program Files\PostgreSQL\17\bin\psql.exe" -h localhost -p 5432 -U postgres -d CattleTrackingDB -c "ALTER TABLE \"LocationHistories\" ALTER COLUMN \"AnimalId\" DROP NOT NULL;"
echo Making TrackerId nullable...
"C:\Program Files\PostgreSQL\17\bin\psql.exe" -h localhost -p 5432 -U postgres -d CattleTrackingDB -c "ALTER TABLE \"LocationHistories\" ALTER COLUMN \"TrackerId\" DROP NOT NULL;"
echo Creating indexes...
"C:\Program Files\PostgreSQL\17\bin\psql.exe" -h localhost -p 5432 -U postgres -d CattleTrackingDB -c "CREATE INDEX IF NOT EXISTS \"IX_LocationHistories_DeviceId\" ON \"LocationHistories\" (\"DeviceId\");"
"C:\Program Files\PostgreSQL\17\bin\psql.exe" -h localhost -p 5432 -U postgres -d CattleTrackingDB -c "CREATE INDEX IF NOT EXISTS \"IX_LocationHistories_Timestamp\" ON \"LocationHistories\" (\"Timestamp\" DESC);"
echo All database fixes completed successfully!